services:

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: ordersdb
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  api:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      PORT: 3100
      MONGO_URL: mongodb://mongo:27017/ordersdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      DISABLE_RABBITMQ: 'false'
    ports:
      - '3100:3100'
    command: ["node","dist/index.js"]

volumes:
  mongo_data:
